### ISSUE TITLE
License issue with Octomap and Octomap viewer

### ISSUE THREAD

**Issue by bernabei24** [OctoMap/octomap#121]
Octomap package has a BSD license as see below, however it includes the octovis viewer in the source of the package. The octovis viewer has a GPL v2 license that is not BSD and is unusable and should be removed from the octomap package.

<package> 
2   <name>octomap</name> 
3   <version>1.8.0</version> 
4   <description>The OctoMap library implements a 3D occupancy grid mapping approach, providing data structures and mapping algorithms in C++. The map implementation is based on an octree. See 
5   http://octomap.github.io for details.</description> 
6 
7   <author email="wurm@informatik.uni-freiburg.de">Kai M. Wurm</author> 
8   <author email="armin@hornung.io">Armin Hornung</author> 
9   <maintainer email="armin@hornung.io">Armin Hornung</maintainer> 
10   <license>BSD</license

**Comment by ahornung** [comment]
You are right, the octomap package is BSD licensed and octovis GPL due to including QGLViewer. 

But octomap is not linking octovis in any way, it's the other way around. Note that the octomap "distribution" repository contains 3 different packages, all with their own license. 
-- 
* Sent from a mobile device, please excuse my brevity *
