### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by ThadeuVBrito** [OctoMap/octomap#178]
Hello, I have a problem with the collision detection with the octomap server. The screenshot best indicates my problem, can anyone tell me what I'm doing wrong?
![rviz_screenshot_2017_07_09-19_43_35](https://user-images.githubusercontent.com/29926059/28218628-ffb30d38-68b0-11e7-9b84-8e186fd7bdff.png)

**Comment by ahornung** [comment]
There's no collision avoidance directly in octomap_server, I assume you're using MoveIt! instead? The question is then better suited for [ros-planning/moveit](https://github.com/ros-planning/moveit)

**Comment by ThadeuVBrito** [comment]
Thanks!

**Comment by cgkrishnan** [comment]
Hi @ThadeuVBrito I am also facing a similar issue, were you able to get any leads on the same.

Regards,
Gautam.

**Comment by ThadeuVBrito** [comment]
Hello @cgkrishnan unfortunately not yet, I still search a solution for this. In my searching about collisions in MoveIt I found this [link](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pr2_tutorials/planning/src/doc/perception_configuration.html). But I couldn't reach what goal of this tutorial.
If you have success can you tell me?

**Comment by jkira33** [comment]
I also faced a  similar issue. In my case, it didn't work with point_cloud.yaml , but  rgbd.yaml works pretty good.  I am facing another issue that when occupied voxels touch the ground ( the grid in rviz), my robot base turns to red (I think the robot base is collision with occupied voxels). However , there is no voxels around the base. Anyone have some suggestions? Thanks

**Comment by Ricolus** [comment]
Hello, I am facing the same problem now. I implemented a kinect sensor in gazebo and publish the point cloud. In RViz the point cloud is visualized. Unfortunately move_group doesn't recognize it when planning the path for the robot arm. How can I connect the point cloud with the planning scene? so that it avoids the obstacles?
Cheers Marco

**Comment by MarcoT11** [comment]
Hello, I am facing the same problem now. I implemented a kinect sensor in gazebo and publish the point cloud. In RViz the point cloud is visualized. Unfortunately move_group doesn't recognize it when planning the path for the robot arm. How can I connect the point cloud with the planning scene? so that it avoids the obstacles?
Cheers Marco

**Comment by ThadeuVBrito** [comment]
Hello @MarcoT11 , You need to publish the Point Cloud. So the move_group "will see" the occupied voxels.
