### ISSUE TITLE
New release after #406

### ISSUE THREAD

**Issue by domire8** [OctoMap/octomap#412]
Hi there!

Any chance there could be a new patch version after #406? This is a great fix and would be great to have a tagged version for this.

Thank you!

**Comment by wxmerkt** [comment]
Hi @ahornung 
I agree - we should have a new release. Can we please get the following PRs merged first (both minor and CI/ROS-release related):
1. https://github.com/OctoMap/octomap/pull/408
2. https://github.com/OctoMap/octomap/pull/413

The diff between the last release (1.9.8) and master is the following: https://github.com/OctoMap/octomap/compare/v1.9.8...devel - we may need to bump the minor version rather than a patch version?

What do you think?

**Comment by clalancette** [comment]
We also need this to be released in order to make octomap build on Noble; see https://build.ros2.org/job/Rbin_uN64__octomap__ubuntu_noble_amd64__binary/8/console .  In particular, we need https://github.com/OctoMap/octomap/pull/373 released so it will build cleanly.

It would also be nice to get #415 in, though it isn't strictly required to make it build (it will just have warnings).

**Comment by ahornung** [comment]
Thanks! I'll have a look asap. Traveling right now, so it will be in a few days.

**Comment by ahornung** [comment]
@wxmerkt  @clalancette  thanks, looking good so far with the PRs! Updated release coming soon.

**Comment by clalancette** [comment]
> @wxmerkt @clalancette thanks, looking good so far with the PRs! Updated release coming soon.

Thank you, much appreciated!

**Comment by ahornung** [comment]
Done, v1.10.0 released!

**Comment by clalancette** [comment]
> Done, v1.10.0 released!

Fantastic, thank you so much.  Are you planning on doing a bloom-release of this for ROS 2, or would you prefer that I do it?

**Comment by ahornung** [comment]
I'm not really tracking or maintaining the ROS releases anymore, so if either @wxmerkt  or you do it that's fine by me.

**Comment by clalancette** [comment]
> I'm not really tracking or maintaining the ROS releases anymore, so if either @wxmerkt or you do it that's fine by me.

All right, I'll go ahead and do it.

**Comment by clalancette** [comment]
And here is the release into Rolling: https://github.com/ros/rosdistro/pull/40273

**Comment by wxmerkt** [comment]
Thank you for the time to review, merge, and release @ahornung - much appreciated.

@clalancette Thanks for making the release. I had some issues with bloom-release creating the release but not opening the PR

**Comment by domire8** [comment]
Thank you all, much appreciated!
